version: '3.9'
services:
  environment:
    build:
      context: ./
      dockerfile: Dockerfile.environment
    image: 3ket-environment:dev
    ports:
    - "3000:3000"
    volumes:
    - .:/app
    env_file:
      - docker.env
